---
# tasks file for ceph.deployment

# BASIC CONFIGURATION -----------------------------

- name: Customize remote hosts
  import_tasks: customize_hosts.yml

- name: Configure Docker environment
  import_tasks: docker_configuration.yml

- name: Configure Ceph environment
  import_tasks: ceph_configuration.yml

# CUSTOM CONFIGURATION -----------------------------

# RESUME CLUSTER DEPLOYMENT -----------------------------

- name: Show deployment status
  import_tasks: show_resume_deployment.yml
